### ISSUE TITLE
Not Persisting After Restart

### ISSUE THREAD

**Issue by unwisegeek** [Percedal/FS22_UpgradableFactories#11]
Love the mod! 

The issue I've found is it's not saving changes to the production point after saving and restarting the game. The factory I upgraded was the GrainQuid Pro silo mod.  This is on No Man's Land.

I'm attaching log.txt. Is there anything else you'd like?

Thanks!
[log.txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10188157/log.txt)

**Comment by lordbanastor** [comment]
I have the same issue, but some different behaviour: I have 2 greenhouses. I upgraded both, but only one remains upgraded after a restart. I tried renaming both to see if it helps, but was to no avail. I loved the mod, by the way. Keep up the nice work!

**Comment by Percedal** [comment]
> The issue I've found is it's not saving changes to the production point after saving and restarting the game. The factory I upgraded was the GrainQuid Pro silo mod. This is on No Man's Land.

do you have a like on modhub for Grain Quid silo ?

**Comment by lordbanastor** [comment]
No, I don't have this specific mod.

**Comment by unwisegeek** [comment]
https://www.farming-simulator.com/mod.php?lang=en&country=us&mod_id=245188&title=fs2022

**Comment by SteamWizard** [comment]
I'm having the same issue as lordbanastor. I have multiple iron smelters, but only the upgrades to the first one persist after loading a save. Great mod none the less.

**Comment by saren42** [comment]
Also having the issue of only 1 base game greenhouse remembering the level, but only for a single restart. When you start the game after saving and quiting it doesn't remember the one it originally remembered.

AKA, Play game, level up 2 greenhouses to level 5, save and quit, reload, greenhouse 1 == level 5; greenhouse 2 == level 1. Save game, and quit. Reload, greenhouse 1 == level 1; greenhouse 2 == level 2. 

Monitoring 'upgradableFactories.xml', after the first save and quit, both would show as level 5. After the 2nd save and quit, it only shows greenhouse 1 as level 5. After the 3rd save and quit, it shows both at level 1.

In all occurrences, it does retain the upgraded base price though, so it would cost the same to upgrade to level 2, as it would normally cost to upgrade to level 2 now on the previously upgraded greenhouse.

If you want any more details or some sort of logs (not sure what exists for logs for FS22), let me know, I'll get you what I can.

**Comment by Percedal** [comment]
Thank you for your help, that's really usefull. I've an idea of what's possibly going wrong.
where your greenhouses close to each other?

**Comment by saren42** [comment]
Indeed they are, they are adjacent to each other in a row.

Something else I did notice, was the base value from slot 1 only.

**Comment by Percedal** [comment]
this will be fixed in the next patch
