### ISSUE TITLE
save file stuck at 99%

### ISSUE THREAD

**Issue by qahtmm3f** [Percedal/FS22_UpgradableFactories#12]
after i get in the game and upgarde a factory. and close the game. i can't load it again. as it stay 99%

i disable the mod the save file loads no problem.

**Comment by qahtmm3f** [comment]
[log.txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10201940/log.txt)

sry this is my log file

**Comment by Percedal** [comment]
This is a known issue and it will be fixed in the v1.1.0.0 patch.
It appears when saving the game while having no owned productions (upgradableFactories.xml remains empty).
For right now, removing `upgradableFactories.xml` from your savegame will allows you to load the game properly.

**Comment by qahtmm3f** [comment]
allright thank you. noted. let me know if i shou;d close it or leave it coz i am new to this github thingy :)

**Comment by Percedal** [comment]
@qahtmm3f 
> allright thank you. noted. let me know if i shou;d close it or leave it coz i am new to this github thingy :)

don't worry for that.

@Iwan1803 Ok i wasn't aware of that bahaviour with PnH dlc, that's quite strange. I suspect that might be related to an other issue. thank you for bringing the problem to my attention.
