### ISSUE TITLE
Translation BR

### ISSUE THREAD

**Issue by Myiamoto86** [Percedal/FS22_UpgradableFactories#13]
Dear friend, good afternoon.

I have the BR translation of your mod, I want to have the honor to share it to be added in a next update.

Note: Congratulations, you made a very cool mod.

Hugs.
[modDesc.txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10260706/modDesc.txt)

**Comment by Percedal** [comment]
thank you very much

**Comment by Myiamoto86** [comment]
Any additional item, I will be at your disposal.
