### ISSUE TITLE
Some of my productions are resetting levels after save and restarts

### ISSUE THREAD

**Issue by OrganicSugar** [Percedal/FS22_UpgradableFactories#18]
I am using this with other mods so there may be a conflict. But I upgraded 2 different olive/grape greenhouses to level 4 this morning. Then after coming back one of my level 4 greenhouses became level 1 and another completely random greenhouse became level 4 and even randomly got the water I put into the original olive greenhouse. The 2 mods I am using with the greenhouses are the [Multi-Crop Greenhouses Pack] and the [Greenhouse and Nursery], all from FS22 Official Modhub. Note, I haven't even used/upgraded/or even filled the Very Large Greenhouse yet. I also checked the upgradableFactories.xml in my save file and all the correct information is there. Like all the proper greenhouses have been upgraded in the XML file.
![image](https://user-images.githubusercontent.com/121600255/209914316-e9e94d87-1c3e-4ae5-ada1-68e8df555153.png)
![image](https://user-images.githubusercontent.com/121600255/209914266-c3039042-7e50-453a-a7c1-0a38a413ab56.png)

**Comment by Percedal** [comment]
Are these 2 greenhouses close to each other? If so it will be patched in the next update.

**Comment by OrganicSugar** [comment]
Yeah, they are next to each other

**Comment by Percedal** [comment]
well given the Giants hollidays and the mod testing queue, I don't think it will be before mid-January.
