### ISSUE TITLE
Greenhouses resetting

### ISSUE THREAD

**Issue by wafflehatjoe** [Percedal/FS22_UpgradableFactories#19]
Greenhouses seem to randomly reset to level 1 after restarting the game. The cost of upgrading also seems to get messed up when this happens.

Upgrade prices the first time before they reset start at $11,000>$12,000>$13,000>$14,000 and so on. After coming back to play my green houses were back to level 1, but the price to upgrade from level 1 to 2 was $60,000+, and even with enough money it would tell me "You don't have enough money"

**Comment by Percedal** [comment]
This is a known issue and will be fixed in the upcoming patch
