### ISSUE TITLE
Reinstalled

### ISSUE THREAD

**Issue by VortexGT** [Percedal/FS22_UpgradableFactories#20]
Because of the PnH DLC issue I had to reinstall this mod and and when I tried to upgrade previously upgraded buildings it costs more than it should.   Example I had 1 sugar mill upgraded to level 2 then I ended up uninstalling then reinstalling this mod which caused me to lose that upgrade.   When going back in and trying to upgrade the same building back to level 2 it now costs double what It actually should for a level 2 upgrade.

**Comment by Percedal** [comment]
Yeah i see what's going on and i've seen it comming tbh...
Basically when upgrading production's value is increase and default price is overwritten and stored when saving.
Right now the work around is to manually set the production price in `placeables.xml` to it's default value.

**Comment by Percedal** [comment]
This will fixed in the comming release
