### ISSUE TITLE
Downgrade button

### ISSUE THREAD

**Issue by 60erjonny** [Percedal/FS22_UpgradableFactories#21]
Hallo, vielen Dank für diesen Mod...! Es klingt vieleicht etwas überheblich, aber interessant hier wäre auch, die Aufrüstungsstufe wieder rückgäng machen zu können...

**Comment by Percedal** [comment]
Being able to downgrade a production is possible but a not priority.
To be fair i've already thought about it but not implemented yet.
(Please use english)
