### ISSUE TITLE
I removed the mod, now my productions are incredibly expensive

### ISSUE THREAD

**Issue by Evilchicken98** [Percedal/FS22_UpgradableFactories#27]
Map Gnadenthal
I upgrade my 12 Growhouses to lv.2 after a first restart only 6 are still lv.2 after a third restart only 3 lv.2.
It seems like its not saving anything.
I think the problem is that on this savegame i used multiple versions of that mod i removed it several times to reset upgrades for all factories after that productions like the tailor cost 18 million to upgrade to lv.2 the value didnt reset.
Im using platinum and P&H + default productions + mod sawmill and many other mods.
I tried several ways to fix it sold all productions build everything new same ending nothing works.
I believe this savegame is just not working with this anymore.
3 xml inside the zip folder.
[log ..1st restart.txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10418818/log.1st.restart.txt)
[log ..2nd restart...txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10418819/log.2nd.restart.txt)
[log ..before restart...txt](https://github.com/Percedal/FS22_UpgradableFactories/files/10418820/log.before.restart.txt)
[upgradableFactories ..before restart.zip](https://github.com/Percedal/FS22_UpgradableFactories/files/10418824/upgradableFactories.before.restart.zip)

**Comment by Percedal** [comment]
yeah pre-v1.2 remove the mod while having upgraded productions was messing things up. basically the placeable value was overwritted in the placeable.xml file. thus, a BGA level 10 that have a total value of 11M€ would still be worth that even if the mod was removed.
Your savegame is not lost but you may have to go through your productions in placeable.xml file and check if the values are the default ones (aka the price you pay to place it). and i get it, that's a bit tedious knowing the number of productions you have.

**Comment by Evilchicken98** [comment]
I just checked the placeables.xml the value is normal for example a greenhouse is 10k everything else seems normal too.
During fixing i demolished every Production there cant be a production that has old values or is a building not removed from the xml after demolishing? 
I demolished every production then removed the mod completly deleted the upgradefactory.xml and started again first i tested with 5 greenhouses and nothing else upgrade to lv.2 save, leave, restart it worked then placed every prod. again 24 greenh. to lv.2 save, leave, restart 12 on lv.1 i dont know very strange.

**Comment by Percedal** [comment]
very strange as you said, can share your savegame for better investigations?

**Comment by Evilchicken98** [comment]
[savegame4.zip](https://github.com/Percedal/FS22_UpgradableFactories/files/10436476/savegame4.zip)

**Comment by Percedal** [comment]
it seems that something was still problematic when loading productions from xml, it's beeing fixed.
Thanks for your help

**Comment by Evilchicken98** [comment]
Thats good glad to hear that.
