### ISSUE TITLE
Sorting production menu

### ISSUE THREAD

**Issue by Switty003** [Percedal/FS22_UpgradableFactories#30]
Hello, Production Revamp sorts the productions in the menu alphabetically. Since you write the upgrade level in front, it sorts by the numbers. Is it possible to write the number somewhere else so that Revamp's sorting stays the same?

**Comment by Percedal** [comment]
To be honest with you, UF and P. Revamp modify the same game mechanics whiwh makes them hardly compatible. Keeping up with mod updates and making sure the 2 mods are compatible is really time consuming and it's not a valid sollution in time.
Right i don't have the time to reengineer th UI.
