### ISSUE TITLE
Multiplayer support

### ISSUE THREAD

**Issue by Harag9** [Percedal/FS22_UpgradableFactories#31]
I've just started on a server with a few friends and all fairly new to FS22, and love the sound of this mod as we're finding we're having to build "industrial parks", however on the giants modhub page it says it doesn't support multiplayer, yet on the front page here it doesn't mention it.

Can you confirm if it support MP / server or not. and if not - any idea if you will be implementing it to support MP and when? Many thanks for what looks to be a great mod idea.

**Comment by Percedal** [comment]
MP is not supported and i don't know when it will.

**Comment by Kodi4444** [comment]
I would love Multiplayer support. what are the main issues with implementing this?

**Comment by Percedal** [comment]
right now, i don't have the time to port the mod to mp. Tbh i don't know how multiplayer modding work in this game... so i have to figure that out which takes an absolutely crazy amount of time
